/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sharma ji (https://sketchfab.com/vfxstudio987)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jbl-headphone-changeable-colour-fceab67bac8f4d1f8331197305da3dda
Title: JBL Headphone (changeable colour )
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
const Headphones = (props) => {
  const targetRef = useRef();

  useGSAP(() => {
    // Animate position (up and down)
    gsap.to(targetRef.current.position, {
      y: targetRef.current.position.y + 0.5,
      duration: 1.5,
      repeat: -1,
      yoyo: true,
    });
  });
  const { nodes, materials } = useGLTF("/models/headphone-2.glb");
  return (
    <group {...props} dispose={null} ref={targetRef}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface4_upper_body1_0.geometry}
        material={materials.upper_body1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface5_upper_inner_body_0.geometry}
        material={materials.upper_inner_body}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Joint_middle_body_0.geometry}
        material={materials.middle_body}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface8_plud_body_0.geometry}
        material={materials.plud_body}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder1_ear_plug_0.geometry}
        material={materials.ear_plug}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCylinder2_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface2_Default_Material_0.geometry}
        material={materials.Default_Material}
      />
    </group>
  );
};

useGLTF.preload("/models/headphone-2.glb.glb");

export default Headphones;
