/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Eternal Realm (https://sketchfab.com/EternalRealm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/playstation-vr-645bb34486a54e618247c51c98f56205
Title: Playstation VR
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
const PlaystationVR = (props) => {
  const targetRef = useRef();
  const { nodes, materials } = useGLTF("/models/saxophone.glb");

  useGSAP(() => {
    // Animate position (up and down)
    gsap.to(targetRef.current.position, {
      y: targetRef.current.position.y - 0.5,
      duration: 1.4,
      repeat: -1,
      yoyo: true,
    });
  });
  return (
    <group ref={targetRef} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-3.744, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.psvr_Circle001_0.geometry}
            material={materials.black}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.psvr_Circle001_1.geometry}
            material={materials.logo}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.psvr_Circle001_2.geometry}
            material={materials.white}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.psvr_Circle001_3.geometry}
            material={materials.screen}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.psvr_Circle001_4.geometry}
            material={materials.BakedCycles}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.psvr_Circle001_5.geometry}
            material={materials.blue}
          />
        </group>
        <group
          position={[1.502, 0, 0.868]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.627}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.move_Circle000_0.geometry}
            material={materials.ball}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.move_Circle000_1.geometry}
            material={materials.base}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.move_Circle000_2.geometry}
            material={materials.ball2}
          />
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/saxophone.glb");

export default PlaystationVR;
